export const homeObjOne = {
    lightBg: false,
    imgStart: '',
    lightTopLine: true,
    lightText: true,
    lightTextDesc: true,
    primary: true,
    topLine: 'Читальня',
    headline: '«Территория эмоций»',
    description: 'Книжный клуб, место встреч, клуб настольных игр, беседы с поэтами и писателями, вечера авторской песни, студия «открытый микрофон», коворкинг.',
    buttonLabel: 'Вступить',
    start: '',
    img: require('../../images/react-plug.svg').default,
    alt: 'IMAGE',
};

export const homeObjTwo = {
    lightBg: true,
    imgStart: 'start',
    lightTopLine: false,
    lightText: false,
    lightTextDesc: false,
    primary: false,
    topLine: '???',
    headline: 'Что это за место?',
    description: '«Территория эмоций» — внестационарный пункт обслуживания Центральной городской библиотеки Нижнего Новгорода с функцией читального зала.\nЭто уникальная площадка для всестороннего развития эмоционального интеллекта, уровня взаимодействия и коммуникации людей всех поколений, а также гармоничного развития личности.',
    buttonLabel: 'Вступить',
    start: 'true',
    img: require('../../images/img-1.jpg'),
    alt: 'IMAGE',
};

export const homeObjThree = {
    lightBg: false,
    imgStart: '',
    lightTopLine: true,
    lightText: true,
    lightTextDesc: true,
    primary: false,
    topLine: 'Развлечения',
    headline: 'Чем можно заняться?',
    description: 'На площадке проходят занятия по арт-терапии, нейрографике, психологические мастерские, медитативные практики, встречи с интересными персонами, обсуждение актуальных тем и лекции.\nФонд читального зала «Территории эмоций» составляет 400 книжных новинок: нон-фикшн по саморазвитию, книги по психологии, литература об эмоциях и эмоциональном интеллекте, художественные произведения, мотивы и поступки героев которых интересно и полезно обсуждать.',
    buttonLabel: 'Вступить',
    start: '',
    img: require('../../images/img-2.jpg'),
    alt: 'IMAGE',
};
